-- ============================================================
-- Climate-life — Supabase backend (database) sxemasi
-- ------------------------------------------------------------
-- Bu faylni Supabase loyihangizda:
--   Dashboard → SQL Editor → New query → (shu kodni joylang) → Run
-- orqali bir marta ishga tushiring.
-- ============================================================

-- ---------- 1. JADVALLAR ----------

-- Xizmatlar
create table if not exists public.services (
  id          bigint generated by default as identity primary key,
  type        text    not null default 't1',      -- t1 = xolodilnik, t2 = konditsaner
  icon        text    default '🔧',
  badge       text    default '',
  title       text    not null,
  description text    default '',
  features    text[]  default '{}',
  price_from  text    not null default '0',
  sort        int     default 0,
  created_at  timestamptz default now()
);

-- Ustalar
create table if not exists public.masters (
  id          bigint generated by default as identity primary key,
  name        text not null,
  role        text not null,
  photo       text default '',
  experience  text default '1 yil',
  orders      text default '0',
  rating      text default '4.5',
  tags        text[] default '{}',
  created_at  timestamptz default now()
);

-- Sharhlar
create table if not exists public.reviews (
  id          bigint generated by default as identity primary key,
  name        text not null,
  meta        text default '',
  rating      int  default 5,
  text        text not null,
  created_at  timestamptz default now()
);

-- Savol-javob (FAQ)
create table if not exists public.faq (
  id          bigint generated by default as identity primary key,
  question    text not null,
  answer      text not null,
  sort        int  default 0,
  created_at  timestamptz default now()
);

-- Buyurtmalar (mijozlardan keladi)
create table if not exists public.orders (
  id          bigint generated by default as identity primary key,
  device      text not null,           -- xolodilnik | konditsaner
  problem     text not null,
  name        text not null,
  phone       text not null,
  address     text default '',
  msg         text default '',
  status      text not null default 'yangi',   -- yangi | jarayonda | bajarildi | bekor
  created_at  timestamptz default now()
);

-- ---------- 2. ROW LEVEL SECURITY (xavfsizlik) ----------
-- Maqsad:
--   * Har kim (mehmon) xizmat/usta/sharh/FAQ ni O'QIY oladi
--   * Har kim buyurtma YUBORA oladi (insert)
--   * Faqat tizimga kirgan admin ma'lumotlarni o'zgartira/o'chira oladi
--     va buyurtmalarni ko'ra oladi

alter table public.services enable row level security;
alter table public.masters  enable row level security;
alter table public.reviews  enable row level security;
alter table public.faq      enable row level security;
alter table public.orders   enable row level security;

-- Ommaviy o'qish (services, masters, reviews, faq)
create policy "ommaviy o'qish: services" on public.services for select using (true);
create policy "ommaviy o'qish: masters"  on public.masters  for select using (true);
create policy "ommaviy o'qish: reviews"  on public.reviews  for select using (true);
create policy "ommaviy o'qish: faq"      on public.faq      for select using (true);

-- Admin (kirgan foydalanuvchi) to'liq boshqaruv
create policy "admin yozish: services" on public.services for all to authenticated using (true) with check (true);
create policy "admin yozish: masters"  on public.masters  for all to authenticated using (true) with check (true);
create policy "admin yozish: reviews"  on public.reviews  for all to authenticated using (true) with check (true);
create policy "admin yozish: faq"      on public.faq      for all to authenticated using (true) with check (true);

-- Buyurtmalar: har kim yubora oladi, faqat admin ko'ra/o'zgartira/o'chira oladi
create policy "mehmon buyurtma yuboradi" on public.orders for insert with check (true);
create policy "admin buyurtmalarni ko'radi"     on public.orders for select to authenticated using (true);
create policy "admin buyurtmani o'zgartiradi"   on public.orders for update to authenticated using (true) with check (true);
create policy "admin buyurtmani o'chiradi"      on public.orders for delete to authenticated using (true);

-- ---------- 3. STANDART (boshlang'ich) MA'LUMOTLAR ----------

insert into public.services (type, icon, badge, title, description, features, price_from, sort) values
('t1','🧊','Mashhur','Xolodilnik kompressorini almashtirish','Sovutmaydigan, doim ishlaydigan yoki shovqin chiqaradigan xolodilniklar uchun.', array['Diagnostika bepul','Original kompressor','12 oy kafolat'], '350 000', 1),
('t1','❄️','','Frion quyish (gaz to''ldirish)','Xolodilnik sovutmay qolgan bo''lsa, frion sizib ketgan bo''lishi mumkin.', array['Tez bajariladi','Sizish joyini topamiz','6 oy kafolat'], '200 000', 2),
('t1','🔌','','Termostat va boshqaruv platasi ta''miri','Displey ishlamasa, harorat noto''g''ri ko''rsatsa yoki o''chib qolsa.', array['Plata diagnostikasi','Zapchast almashtirish','6 oy kafolat'], '150 000', 3),
('t2','🫧','Mashhur','Konditsaner gaz to''ldirish / freon','Konditsaner sovutmay qolgan bo''lsa, freon to''ldiramiz va sizishni tekshiramiz.', array['1 kunda tayyor','Original freon','6 oy kafolat'], '180 000', 4),
('t2','⚙️','','Konditsaner kompressor / motor ta''miri','Tashqi blok ishlamasa, kompressor yoki ventilator motori ta''miri.', array['Tez diagnostika','Sifatli zapchast','12 oy kafolat'], '250 000', 5),
('t2','🔧','','Konditsaner tozalash va profilaktika','Suv oqishi, yomon hid yoki kam sovutish — to''liq tozalash xizmati.', array['Uyda tozalash','Filtr yangilash','Kafolat'], '120 000', 6);

insert into public.masters (name, role, photo, experience, orders, rating, tags) values
('Aziz Rahimov','Bosh usta — Xolodilnik','https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=300&q=80','9 yil','1 200+','4.9', array['Kompressor','Frion','Plata']),
('Bobur Yusupov','Usta — Konditsaner','https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&q=80','7 yil','980+','4.8', array['Freon','Motor','Montaj']),
('Davron Karimov','Usta — Universal texnika','https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=300&q=80','6 yil','760+','4.9', array['Diagnostika','Elektronika']),
('Sherzod Tursunov','Usta — Xolodilnik','https://images.unsplash.com/photo-1556157382-97eda2d62296?w=300&q=80','5 yil','540+','4.7', array['Termostat','Gaz to''ldirish']);

insert into public.reviews (name, meta, rating, text) values
('Madina Yusupova','Chilonzor, Toshkent',5,'Xolodilnikim 3 kun ishlamay qoldi. Qo''ng''iroq qilganimdan keyin 40 daqiqada usta keldi, kompressorni almashtirib ketdi. Hozir a''lo ishlaydi!'),
('Jasur Aliyev','Yunusobod, Toshkent',5,'Konditsaner sovutmay qolgan edi. Usta kelib freon to''ldirdi, narxi ham aytilganidan oshmadi. Tavsiya qilaman.'),
('Nodira Saidova','Mirzo Ulug''bek, Toshkent',4,'Diagnostika bepul bo''lgani juda yoqdi. Usta professional, ishini tez va sifatli bajardi. Kafolat varaqasi ham berdi.'),
('Otabek Nazarov','Shayxontohur, Toshkent',5,'Frion sizib, xolodilnik sovutmay qolgandi. Bir kunda hammasini tuzatishdi. Narxlar ham bozordagidan past ekan.');

insert into public.faq (question, answer, sort) values
('Diagnostika rostdan ham bepulmi?','Ha, agar siz keyinchalik ta''mirlashga rozi bo''lsangiz, diagnostika butunlay bepul. Faqat ta''mirlashdan voz kechilgan holatlarda kichik tashrif to''lovi olinishi mumkin.',1),
('Usta qancha vaqt ichida yetib keladi?','Odatda buyurtma qabul qilingandan so''ng 30–60 daqiqa ichida usta yo''lga chiqadi. Band kunlarda 2 soatgacha bo''lishi mumkin, lekin operator aniq vaqtni oldindan aytadi.',2),
('Qanday kafolat berasiz?','Bajarilgan har bir ish uchun yozma kafolat varaqasi beriladi. Kafolat muddati nosozlik turiga qarab 3 oydan 12 oygacha bo''ladi.',3),
('To''lovni qachon va qanday amalga oshiraman?','To''lov ish tugagandan keyin, naqd pul yoki Click/Payme orqali amalga oshiriladi. Oldindan to''lov talab qilinmaydi.',4),
('Texnikam bu yerda ko''rsatilmagan brend bo''lsa-chi?','Muammo emas — ustalarimiz Samsung, LG, Artel, Bosch, Beko, Gree, Midea, Daewoo va boshqa barcha brendlar bilan ishlay oladi.',5),
('Ehtiyot qismlar narxiga kiradimi?','Yo''q, yuqoridagi narxlar — faqat ish haqi. Ehtiyot qism almashtirish kerak bo''lsa, narxi alohida aytiladi va roziligingizdan keyin o''rnatiladi.',6);


-- ============================================================
-- TUGADI. Endi admin foydalanuvchi yarating:
--   Dashboard → Authentication → Users → Add user
--   (email + parol kiriting, "Auto Confirm" yoqilgan bo'lsin)
-- Shu email/parol bilan saytda #admin paneliga kirasiz.
-- ============================================================